---
- hosts: all
  user: demo
  become: true
  become_user: root

  tasks:
    - name: Add group "nixadmins" to remote server
      group:
        name: nixadmins
        gid: 2010
        state: present
      register: out

    - name: Add user "sysadmin1" to remote server
      user:
        name: sysadmin
        comment: "Privileged User"
        uid: 2001
        group: nixadmins
        append: yes
        shell: /bin/bash
      register: out

    - name: Add user "sysadmin2" to remote server
      user:
        name: david
        comment: "Accountant UnPrivileged User"
        uid: 2002
        group: nixadmins
        shell: /bin/bash
      register: out
     
    - debug: 
        var: out.stdout_lines
