---
- name: Deploy files using a jinja2 template
  hosts: all
  become: true
 
  tasks:
    - name: DEploy the message of the day template
      template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: "0664"

      #tasks:
    - name: Deploy the hostfile 
      template:
        src: hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: "0664"
