---
- hosts: '{{ target }}'
  become: true
  become_user: root
  
  tasks:
    - name: "Update SO RedHat"
      command: /usr/bin/cp /etc/redhat-release /tmp/OSRELEASE.txt
      when: ansible_facts['os_family'] == "RedHat"
    - name: "Update SO Debian"
      command: /bin/cp /etc/os-release /tmp/OSRELEASE.txt
      when: ansible_facts['os_family'] == "Debian"
      #- name: Reboot Server
      #reboot:
